// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjQHCCuFIr0CAgKaHw7rOWIfo0V_m3fE',
    appId: '1:519134177013:web:170c91e3fdc7a120ab87bc',
    messagingSenderId: '519134177013',
    projectId: 'appdemo-162b0',
    authDomain: 'appdemo-162b0.firebaseapp.com',
    storageBucket: 'appdemo-162b0.firebasestorage.app',
    measurementId: 'G-P2TBZL9R74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJEixThv9Ql6JHdmPcJXemRq1C4peV7QE',
    appId: '1:519134177013:android:9cfa4d12a58e4b3fab87bc',
    messagingSenderId: '519134177013',
    projectId: 'appdemo-162b0',
    storageBucket: 'appdemo-162b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhylZToV4PN14wU586Z4rX9xfVHbZqjOo',
    appId: '1:519134177013:ios:047833735df08ba5ab87bc',
    messagingSenderId: '519134177013',
    projectId: 'appdemo-162b0',
    storageBucket: 'appdemo-162b0.firebasestorage.app',
    iosBundleId: 'com.example.buoicuoimobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhylZToV4PN14wU586Z4rX9xfVHbZqjOo',
    appId: '1:519134177013:ios:047833735df08ba5ab87bc',
    messagingSenderId: '519134177013',
    projectId: 'appdemo-162b0',
    storageBucket: 'appdemo-162b0.firebasestorage.app',
    iosBundleId: 'com.example.buoicuoimobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIjQHCCuFIr0CAgKaHw7rOWIfo0V_m3fE',
    appId: '1:519134177013:web:27fabcd969688f8cab87bc',
    messagingSenderId: '519134177013',
    projectId: 'appdemo-162b0',
    authDomain: 'appdemo-162b0.firebaseapp.com',
    storageBucket: 'appdemo-162b0.firebasestorage.app',
    measurementId: 'G-NGWKF1V9CG',
  );

}